spring:
  application:
    name: designmodel # 设置项目启动名称

# 设置连接数据库信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=UTC
# 设置项目启动端口号
server:
  port: 8080

# 设置mapper扫描路径
mybatis:
#  mapper-locations: classpath:mapper/*.xml,classpath:mapper/**/*.xml
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: design.model.domain.entity

# 设置日志打印级别
logging:
  level:
    design:
      model: debug

